#!/usr/bin/env bash
# Script that transfers a file from client to server using scp

# Check number of arguments
if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
else
# Transfering using scp
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~
fi
